# Generated by Django 3.2.16 on 2023-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230429_0605'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_author_text',
        ),
    ]
